AWSTemplateFormatVersion: "2010-09-09"
Description: "Nova Syndicate - CloudWatch Alarms for Sprint 2"

Resources:

  NovaHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: NovaSyndicate-ASG-HighCPU
      AlarmDescription: Alarm when average CPU is higher than 70 percent
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: NovaSyndicate-App-ASG

  NovaALB5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: NovaSyndicate-ALB-5XX
      AlarmDescription: Alarm when ALB returns 5XX errors
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_5XX_Count
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold